import turtle
turtle.shape('turtle')
square= turtle.clone()
square.shape('square')
square.goto(0,0)
square.goto(0,100)
square.stamp()
square.goto(100,100)
square.stamp()
square.goto(100,0)
square.stamp()
square.goto(0,0)
triangle=turtle.clone()
triangle.shape('triangle')
triangle.goto(0,0)
triangle.goto(50,100)
triangle.stamp()
triangle.goto(100,0)
triangle.goto(0,0)
